export const userData = [
  {
    name: 'Alice',
    email: 'alice@example.com',
    password: 'password123',
    grade: 1,
    department: 'Computer Science',
    majar: 'Software Engineering',
    enrolledYear: 2023,
  },
  {
    name: 'Bob',
    email: 'bob@example.com',
    password: 'password456',
    grade: 2,
    department: 'Electrical Engineering',
    majar: 'Electronics',
    enrolledYear: 2022,
  },
  {
    name: 'Carol',
    email: 'carol@example.com',
    password: 'password789',
    grade: 3,
    department: 'Mechanical Engineering',
    majar: 'Robotics',
    enrolledYear: 2021,
  },
  {
    name: 'David',
    email: 'david@example.com',
    password: 'passwordabc',
    grade: 4,
    department: 'Civil Engineering',
    majar: 'Structural Engineering',
    enrolledYear: 2020,
  },
  {
    name: 'Emma',
    email: 'emma@example.com',
    password: 'passwordxyz',
    grade: 1,
    department: 'Chemical Engineering',
    majar: 'Materials Science',
    enrolledYear: 2023,
  },
];
